default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_api_development
  username: blog_api
  password: blog_api

test:
  <<: *default
  database: blog_api_test
  username: blog_api
  password: blog_api

production:
  <<: *default
  database: blog_api_production
  username: blog_api
  password: blog_api
