default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_api_2_development
  username: blog_api_2
  password: blog_api_2

test:
  <<: *default
  database: blog_api_2_test
  username: blog_api_2
  password: blog_api_2

production:
  <<: *default
  database: blog_api_2_production
  username: blog_api_2
  password: blog_api_2
